version: 2
jobs:
  build_and_setup:
    docker:
      - image: ccistaging/android:api-28
    working_directory: ~/project
    environment:
      - JAVA_TOOL_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport"
      - GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"
      - TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
                    sudo chmod +x ./gradlew 
                    ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
      - run:
          name: Build test and lint
          command: |
                    sudo chmod +x ./gradlew 
                    ./gradlew testDebug lintRelease
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex "./.*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
          destination: tests
      - store_artifacts:
          path: ./build/reports
          destination: reports/
      - persist_to_workspace:
          root: .
          paths:
            - ./build
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_setup
