version: 2
jobs:
  build_and_setup:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/project
    environment:
      - FASTLANE_LANE_LINT: lint
      - FASTLANE_LANE_TEST: test
      - JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
      - GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"
      - TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
      - run:
          name: Download Dependencies
          command: |
                    sudo chmod +x ./gradlew 
                    ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
      - run:
          name: Build test and lint
          command: bundle exec fastlane $FASTLANE_LANE_LINT
      - run:
          name: Build Detekt
          command: bundle exec fastlane $FASTLANE_LANE_LINT
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex "./.*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
          destination: tests
      - store_artifacts:
          path: ./build/reports
          destination: reports/
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: sdk/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: sdk/build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - ./build
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_setup
