FASTLANE_HIDE_CHANGELOG = true
FASTLANE_SKIP_UPDATE_CHECK = true
fastlane_version "2.85.0"

default_platform :android

platform :android do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    setup_circle_ci
  end

  desc "Runs all the unit tests"
  lane :unit_tests do
    gradle(task: "testDebug")
    slack_result(message: "*Karhoo Android NSDK* passed unit testing")
  end

  desc "Runs lint and detekt"
  lane :linting do
    gradle(task: "lintRelease")
    gradle(task: "detekt")
    slack_result(message: "*Karhoo Android NSDK* passed detekt and lint")
  end

  desc "New Build"
  lane :beta do
    gradle(task: "assemble")
    gradle(task: "install")
  end

  desc "Messaging"
  lane :slack_result do |values|
    message_text = values[:message]
    slack(
      channel: "#test_circleci",
      message: message_text,
      success: values[:success]
    )
  end

  after_all do |lane|
    slack_result(
      message: "*Karhoo Android NSDK* passed all checks",
      success: true
    )
  end

  error do |lane, exception|
    slack_result(
      message: exception.message,
      success: false
    )
  end
end