FASTLANE_HIDE_CHANGELOG = true
FASTLANE_SKIP_UPDATE_CHECK = true
fastlane_version "2.85.0"

default_platform :android

platform :android do
  before_all do
    ENV["SLACK_URL"] = ""
    setup_circle_ci
  end

  desc "Runs all the unit tests"
  lane :unit_tests do
    gradle(task: "testDebug")
    #slack(
        channel: #mobile-pull-requests,
        message: "*Karhoo Android NSDK* passed unit tests"
    )
  end

  desc "Runs lint and detekt"
  lane :linting do
    gradle(task: "lintRelease")
    gradle(task: "detekt")
    #slack(
        channel: #mobile-pull-requests,
        message: "*Karhoo Android NSDK* passed detekt and lint"
    )
  end

  desc "New Build"
  lane :beta do
    gradle(task: "assemble")
    gradle(task: "install")
  end


  after_all do |lane|
    #slack(
    #  message: "*Karhoo NSDK* has passed unit tests"
    #)
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end

